name: Minio
on:
  push:
    #dev
    branches: ["ci"]

jobs:
  minio-push:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Minio Deploy
        uses: mamal72/minio-perfect-deploy-action@main        
        with:
          endpoint: ${{ secrets.MINIO_ENDPOINT }}
          access_key: ${{ secrets.MINIO_ACCESS_KEY }}
          secret_key: ${{ secrets.MINIO_SECRET_KEY }}
          bucket: ${{ secrets.MINIO_I18N_BUCKET }}
          # Optional inputs with their defaults:
          source_dir: "locales/"
          target_dir: "/"
